query GetProjectItemsOverview {
  ProjectItems {
    items {
      slug
      content {
        name
        short_description
        banner {
          id
          filename
        }
      }
    }
  }
}
